# (PART) Part I {-}

# Getting started

## What is LaTeX? 

## Why LaTeX? 

- Maths 
- Big documents 
- WYWIWYG not WYSIWYG 
- Plain text plays well with version control 
- Been around for a long time and stable
- Programmatic:
  - much more control than markdown 
  - can define your own macros to take some of the faff out of it
- Journals and Books

what to prepare yourself for 

- some very pretty output
- some very ugly error messages 
- a steep but rewarding learning curve 
- lots of googling
 
Effictively learning a programming language, but where the output is a pretty document. 

## Getting LaTeX ready

- Online vs Offline
- Recommend using Overleaf, at least until you get started 
- Worry about installing locally when you want to write on a train or a plane.
- Link to installation instructions 
- IDE vs vim vs commandline


## Where to look for help? 

- The Not so short introduction to LaTeX2e
- Google (and friends)
- Books

## A Note on Directory Structure

- Good to know where things are on your computer 
- Don't work in Downloads or some other ridiculous location 
- Either have a single directory (maybe Documents/writing) to store all of your tex documents in one place 
- If using Overleaf this is effectively what you are doing, but the documents are all stored on the cloud rather than on your computer.
- On a related note - just like you should have backups of word documents incase you spill your pint of squash on your laptop, you should keep your LaTeX files in the cloud or with backups.
- The other apprach, if you are wriing on on exciting project, is to have all files to do with that project in Documents/.../exciting-project/writing 
- This is because in the process of going from plain text to a beautiful pdf, LaTeX will make some intermediate files (which you can delete safely) that contain advanced diagnoistic information  when thing go wrong. You can set things up so that LaTeX will tidy up after itself, but I wouldn't recommend it. Just ignore the extra files until you ever need them. 
